version: '2'

services:
  bcsc-mysql:
    image: mysql:5.6
    command: mysqld_safe
    hostname: bcsc-mysql
    container_name: bcsc-mysql
    mem_limit: 8g
    memswap_limit: 8g
    expose:
      - 3306
    ports:
      - 3307:3306
    volumes:
      - ../blockchain-shared:/tmp/blockchain-shared
      
  bcsc-cassandra1:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra1
    container_name: bcsc-cassandra1
    mem_limit: 8g
    memswap_limit: 8g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9041:9042
    volumes:
      - ../conf:/conf
      - ../blockchain-shared:/tmp/blockchain-shared
      
  bcsc-cassandra2:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra2
    container_name: bcsc-cassandra2
    mem_limit: 8g
    memswap_limit: 8g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9042:9042
    volumes:
      - ../conf:/conf
      - ../blockchain-shared:/tmp/blockchain-shared
    
  bcsc-cassandra3:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra3
    container_name: bcsc-cassandra3
    mem_limit: 8g
    memswap_limit: 8g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
     - 9043:9042
    volumes:
      - ../conf:/conf
      - ../blockchain-shared:/tmp/blockchain-shared
      
  bcsc-cassandra4:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra4
    container_name: bcsc-cassandra4
    mem_limit: 8g
    memswap_limit: 8g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9044:9042
    volumes:
      - ../conf:/conf
      - ../blockchain-shared:/tmp/blockchain-shared

 