/*
 * Swagger PetNutrition YAML
 * Pet Nutrition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pzybrick@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LotSupplierBlockItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LotIngredientItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-21T14:06:51.656Z")
public class LotIngredientItem {
  @SerializedName("ingredientSequence")
  private Integer ingredientSequence = null;

  @SerializedName("ingredientName")
  private String ingredientName = null;

  @SerializedName("lotSupplierBlockItems")
  private List<LotSupplierBlockItem> lotSupplierBlockItems = null;

  public LotIngredientItem ingredientSequence(Integer ingredientSequence) {
    this.ingredientSequence = ingredientSequence;
    return this;
  }

   /**
   * Get ingredientSequence
   * @return ingredientSequence
  **/
  @ApiModelProperty(example = "12", value = "")
  public Integer getIngredientSequence() {
    return ingredientSequence;
  }

  public void setIngredientSequence(Integer ingredientSequence) {
    this.ingredientSequence = ingredientSequence;
  }

  public LotIngredientItem ingredientName(String ingredientName) {
    this.ingredientName = ingredientName;
    return this;
  }

   /**
   * Get ingredientName
   * @return ingredientName
  **/
  @ApiModelProperty(example = "Brown Rice", value = "")
  public String getIngredientName() {
    return ingredientName;
  }

  public void setIngredientName(String ingredientName) {
    this.ingredientName = ingredientName;
  }

  public LotIngredientItem lotSupplierBlockItems(List<LotSupplierBlockItem> lotSupplierBlockItems) {
    this.lotSupplierBlockItems = lotSupplierBlockItems;
    return this;
  }

  public LotIngredientItem addLotSupplierBlockItemsItem(LotSupplierBlockItem lotSupplierBlockItemsItem) {
    if (this.lotSupplierBlockItems == null) {
      this.lotSupplierBlockItems = new ArrayList<LotSupplierBlockItem>();
    }
    this.lotSupplierBlockItems.add(lotSupplierBlockItemsItem);
    return this;
  }

   /**
   * Get lotSupplierBlockItems
   * @return lotSupplierBlockItems
  **/
  @ApiModelProperty(value = "")
  public List<LotSupplierBlockItem> getLotSupplierBlockItems() {
    return lotSupplierBlockItems;
  }

  public void setLotSupplierBlockItems(List<LotSupplierBlockItem> lotSupplierBlockItems) {
    this.lotSupplierBlockItems = lotSupplierBlockItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LotIngredientItem lotIngredientItem = (LotIngredientItem) o;
    return Objects.equals(this.ingredientSequence, lotIngredientItem.ingredientSequence) &&
        Objects.equals(this.ingredientName, lotIngredientItem.ingredientName) &&
        Objects.equals(this.lotSupplierBlockItems, lotIngredientItem.lotSupplierBlockItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ingredientSequence, ingredientName, lotSupplierBlockItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LotIngredientItem {\n");
    
    sb.append("    ingredientSequence: ").append(toIndentedString(ingredientSequence)).append("\n");
    sb.append("    ingredientName: ").append(toIndentedString(ingredientName)).append("\n");
    sb.append("    lotSupplierBlockItems: ").append(toIndentedString(lotSupplierBlockItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

