version: '2'

services:
  bcsc-spark-master:
    image: spark:2.3.0
    command: bin/spark-class org.apache.spark.deploy.master.Master -h bcsc-spark-master
    hostname: bcsc-spark-master
    container_name: bcsc-spark-master
    mem_limit: 16g
    memswap_limit: 16g
    environment:
      MASTER: spark://bcsc-spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./bcsc-shared:/tmp/bcsc-shared
      - ./spark/conf/master:/conf
      
  bcsc-spark-worker1:
    image: spark:2.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://bcsc-spark-master:7077 
    hostname: bcsc-spark-worker1
    container_name: bcsc-spark-worker1
    mem_limit: 16g
    memswap_limit: 16g
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8181
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
      - bcsc-spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8181:8181
    volumes:
      - ./bcsc-shared:/tmp/bcsc-shared
      - ./spark/conf/worker:/conf
      
  bcsc-spark-worker2:
    image: spark:2.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://bcsc-spark-master:7077
    hostname: bcsc-spark-worker2
    container_name: bcsc-spark-worker2
    mem_limit: 16g
    memswap_limit: 16g
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8182
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
      - bcsc-spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8182:8182
    volumes:
      - ./bcsc-shared:/tmp/bcsc-shared
      - ./spark/conf/worker:/conf
     
  bcsc-spark-worker3:
    image: spark:2.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://bcsc-spark-master:7077
    hostname: bcsc-spark-worker3
    container_name: bcsc-spark-worker3
    mem_limit: 16g
    memswap_limit: 16g
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8183
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
      - bcsc-spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8183:8183
    volumes:
      - ./bcsc-shared:/tmp/bcsc-shared
      - ./spark/conf/worker:/conf
     
  bcsc-spark-worker4:
    image: spark:2.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://bcsc-spark-master:7077
    hostname: bcsc-spark-worker4
    container_name: bcsc-spark-worker4
    mem_limit: 16g
    memswap_limit: 16g
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8184
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_INSTANCES: 2
      SPARK_EXECUTOR_CORES: 2
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_DRIVER_MEMORY: 8G
      SPARK_DAEMON_MEMORY: 8G
    links:
      - bcsc-spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8184:8184
    volumes:
      - ./bcsc-shared:/tmp/bcsc-shared
      - ./spark/conf/worker:/conf

