version: '2'

services:
  bcsc-cassandra1:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra1
    container_name: bcsc-cassandra1
    mem_limit: 2g
    memswap_limit: 2g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9041:9042
    volumes:
      - ./cassandra/conf:/conf
      - ./bcsc-shared:/tmp/bcsc-shared
      
  bcsc-cassandra2:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra2
    container_name: bcsc-cassandra2
    mem_limit: 2g
    memswap_limit: 2g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9042:9042
    volumes:
      - ./cassandra/conf:/conf
      - ./bcsc-shared:/tmp/bcsc-shared
    
  bcsc-cassandra3:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra3
    container_name: bcsc-cassandra3
    mem_limit: 2g
    memswap_limit: 2g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
     - 9043:9042
    volumes:
      - ./cassandra/conf:/conf
      - ./bcsc-shared:/tmp/bcsc-shared
      
  bcsc-cassandra4:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra.yaml
    hostname: bcsc-cassandra4
    container_name: bcsc-cassandra4
    mem_limit: 2g
    memswap_limit: 2g
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9044:9042
    volumes:
      - ./cassandra/conf:/conf
      - ./bcsc-shared:/tmp/bcsc-shared
 