version: '2'

services:
  bcsc-webapi:
    image: jetty:9.4.9
    working_dir: /usr/local/jetty/
    command: java -jar start.jar --module=http jetty.http.port=8080
    hostname: bcsc-webapi
    container_name: bcsc-webapi
    mem_limit: 2g
    memswap_limit: 2g
    environment:
      CONTACT_POINT: bcsc-cassandra2
      ENV: dev_docker
      KEYSPACE_NAME: bcsc
    expose:
      - 8080
    ports:
      - 8092:8080
    volumes:
      - ../jetty/webapp-webapi:/usr/local/jetty/webapps
      - ../blockchain-shared:/tmp/blockchain-shared
 
  bcsc-webui:
    image: jetty:9.4.9
    working_dir: /usr/local/jetty/
    command: java -jar start.jar --module=http jetty.http.port=8081
    hostname: bcsc-webui
    container_name: bcsc-webui
    mem_limit: 2g
    memswap_limit: 2g
    environment:
      CONTACT_POINT: bcsc-cassandra2
      ENV: dev_docker
      KEYSPACE_NAME: bcsc
    expose:
      - 8081
    ports:
      - 8093:8081
    volumes:
      - ../jetty/webapp-webui:/usr/local/jetty/webapps
      - ../blockchain-shared:/tmp/blockchain-shared
 