version: '2'

services:
  bcsc-mysql:
    image: mysql:5.6
    command: mysqld_safe
    hostname: bcsc-mysql
    container_name: bcsc-mysql
    mem_limit: 2g
    memswap_limit: 2g
    expose:
      - 3306
    ports:
      - 3307:3306
    volumes:
      - ../blockchain-shared:/tmp/blockchain-shared
